fix(arrow/cdata): importSchema: fix potential panic and optimize
Rewrite the code with strings.Cut and strings.SplitSeq to reduce
allocations, and to fix a potential panic.

Before this patch, the code would panic if a colon was missing;

    CGO_ENABLED=1 go test -v -tags test -run TestUnionSchemaErrors ./arrow/cdata/
    --- FAIL: TestUnionSchemaErrors (0.00s)
        --- FAIL: TestUnionSchemaErrors/+us (0.00s)
    panic: runtime error: index out of range [1] with length 1 [recovered, repanicked]

    goroutine 9 [running]:
    testing.tRunner.func1.2({0x7fc7c0, 0x4000026ab0})
        /usr/local/go/src/testing/testing.go:1872 +0x190
    testing.tRunner.func1()
        /usr/local/go/src/testing/testing.go:1875 +0x31c
    panic({0x7fc7c0?, 0x4000026ab0?})
        /usr/local/go/src/runtime/panic.go:783 +0x120
    github.com/apache/arrow-go/v18/arrow/cdata.importSchema(0x40001c36d0)
        /foo/arrow/cdata/cdata.go:306 +0x1520
    github.com/apache/arrow-go/v18/arrow/cdata.ImportCArrowField(...)
        /foo/arrow/cdata/interface.go:43
    github.com/apache/arrow-go/v18/arrow/cdata.TestUnionSchemaErrors.func1(0x40000e0a80)
        /foo/arrow/cdata/cdata_test.go:188 +0xb0
    testing.tRunner(0x40000e0a80, 0x400020c060)
        /usr/local/go/src/testing/testing.go:1934 +0xc8
    created by testing.(*T).Run in goroutine 8
        /usr/local/go/src/testing/testing.go:1997 +0x364
    FAIL	github.com/apache/arrow-go/v18/arrow/cdata	0.007s
    FAIL

With this patch applied, the code handles the invalid value gracefully;

    CGO_ENABLED=1 go test -v -tags test -run TestUnionSchemaErrors ./arrow/cdata/
    === RUN   TestUnionSchemaErrors
    === RUN   TestUnionSchemaErrors/+us
    === RUN   TestUnionSchemaErrors/+ud
    --- PASS: TestUnionSchemaErrors (0.00s)
        --- PASS: TestUnionSchemaErrors/+us (0.00s)
        --- PASS: TestUnionSchemaErrors/+ud (0.00s)
    PASS
    ok  	github.com/apache/arrow-go/v18/arrow/cdata	0.003s

Signed-off-by: Sebastiaan van Stijn <github@gone.nl>